### ISSUE TITLE
Parameter to disable enemy base from popping up on map automatically

### ISSUE THREAD

**Issue by G-Sgt-Hartman** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#100]
The automatic pop up of the enemy base kind of ruins good RECON work, any chance we could make this an option to remove?

**Comment by Liveandletdie** [comment]
+1 for this option, its way to easy to locate/mark bases

**Comment by MKalat** [comment]
+1 for option like this. Whats recon for if its permanently on ?

**Comment by zerty** [comment]
I see what you mean.
But the base detection is not really here to detect a base per se but to actually represent the links that are providing base protection.

One edit I could do is that the base area and base links are only visible while you are actually in the base area, making it necessary to recon/ infiltrate if you are not sure of what towns are providing the protection

**Comment by Liveandletdie** [comment]
I like that idea, only show the area when a team captures one of the connected towns and has located the base, then if a team recaptures all connected towns hide it again.
