### ISSUE TITLE
Slingload Paradrop and static line drops

### ISSUE THREAD

**Issue by Liveandletdie** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#101]
Add ability to release slingloaded objects with parachute
https://www.youtube.com/watch?v=Q2ZPTjioK3Q (everything in this would be awesome!)
It would be very nice to be able to paradrop in ammo crates into semi hostile areas

Add ability to staticline drop out of all helis
http://www.armaholic.com/page.php?id=25092

**Comment by Yoshi-E** [comment]
Add ability to release slingloaded objects with parachute --> Completed

 staticline drop out of all helis --> maybe
