### ISSUE TITLE
Add better intro and overview cams

### ISSUE THREAD

**Issue by Liveandletdie** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#103]
It seems new players still have a hard time understanding everything in the becti gamemode, in addition they always seem to have difficulties leaving the intro area. I also think the gamemode could use some extra polish to attract more players since numbers seem to be down....in order to solve some of these issues I think we should add in some intro sequences and overview cams (spawns) to the game. Check out the CTI liberation game mode for some ideas of what i am thinking.

**Comment by JonXu007** [comment]
<yea , i remember this kind of intro and outro cams from OFP CTI, where on game end it shows winning side and loosing side bases and HQ,like a bird eye
