### ISSUE TITLE
CASH LOOP BUG

### ISSUE THREAD

**Issue by G-Sgt-Hartman** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#106]
There's something in the code that's making scenarios where players are acquiring HUGE sums of cash ($200,000-$600,00 at times). The reward for killing enemies sometimes gets stuck in a loop, and doesn't stop for minutes, resulting in getting a HUGE amount of $$$.  

ALSO

When transferring cash to another player, that sometimes gets stuck in a loop, sometimes giving the Commander a large amount of cash (way more then what was intended to give).

Thanks for looking into this issue Zerty!

**Comment by zerty** [comment]
That new, I ve never observed that kind of bug before

**Comment by Yoshi-EE** [comment]
Happens very rarely though. Last time it happend to me was about an year ago.

**Comment by zerty** [comment]
Extremely rare thus non critical
