### ISSUE TITLE
Destroy own side building

### ISSUE THREAD

**Issue by JonXu007** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#108]
normally if player places explosive near friendly factory it will be removed but if this player send his AI to do same thing explosive remains and it can be detonated and it will do damage, ( not working with HQ )

**Comment by JonXu007** [comment]
Also same effect is in when you shoot arty on own side building and dismount before shells hit the target

**Comment by HTomJMW** [comment]
seems good
