### ISSUE TITLE
Money Transfer

### ISSUE THREAD

**Issue by Yoshi-EE** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#124]
"Yesterday evening on server i had the problem, that i could'nt transfer money to players.
I played bluefor com. Some other players had the problem too, some not. 

Message said something like: "Request to transfer funds to XY has been sent to server"

But no funds were transfered at all.

Problem persisted over at least 2 different game rounds."
--Pace

http://www.jammywarfare.eu/forum/topic.php?id=328

**Comment by zerty** [comment]
corrected @ next restart
