### ISSUE TITLE
MapCommandMenu only have name of groups without name of players

### ISSUE THREAD

**Issue by PR9INICHEK** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#125]
![MapCommandMenu Issue](http://i.imgur.com/Qt9kbds.jpg)

I think code that we need place in **Events_UI_MapCommandMenu.sqf**
`uiNamespace setVariable ["cti_dialog_ui_mapcommandmenu_groups", _groups];`

If we change it to:
`{
        uiNamespace setVariable ["cti_dialog_ui_mapcommandmenu_groups", if (isPlayer leader _x) then {name leader _x} else {"(AI)"}];
        } forEach _groups;`

Get we the result?

**Comment by zerty** [comment]
I did not even thougth that someone was still using that

**Comment by PR9INICHEK** [comment]
Commander don't use it, cause orders not to send players =(
It's good feature for connection Commander->Players

**Comment by Yoshi-E** [comment]
reworking this system might be useful, if players get correct waypoints.
