### ISSUE TITLE
Expend Online Help

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#14]

**Comment by MKalat** [comment]
I suppose there should be more information about how to get commander role, where player should click for it (not everyone knows that this function is in MHQ menu now), and general information about role of commander more deeply covering topics of building and defending base facilities, setting tasks for friendly units. I could write some of this, in my spare time.

**Comment by zerty** [comment]
Yeah sure, it would be great if you could give a hand at this.

Everything is contained in Benny-Edition-CTI-0.97-Zerty-Modification/Client/Events/Events_UI_OnlineHelpMenu.sqf

**Comment by MKalat** [comment]
Thanks for info.
