### ISSUE TITLE
SanitizeAircraftFFAR don't work correctly

### ISSUE THREAD

**Issue by PR9INICHEK** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#140]
Rockets available without any upgrades
![default](https://cloud.githubusercontent.com/assets/9638895/23852083/2ee1653e-07f7-11e7-8f70-d4126d6ff00f.jpg)

**Comment by HTomJMW** [comment]
_specialweapons = ["Rocket_03_AP_F","Rocket_03_HE_F","Rocket_04_AP_F","Rocket_04_HE_F","M_AT"];

M_AT!

**Comment by HTomJMW** [comment]
maybe now ok?

**Comment by Yoshi-E** [comment]
resolved in next update
