### ISSUE TITLE
Rearm distant units

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#149]
From discord
> if i'm not in base. Like, i buy a drone, support myself in the fron with it, land it in base while being in combat at the front, drive it 1 meter range from ammo factory, but cant rearm it because its nit in the list in tablet
> also very big inconvenience for me is that the GBU drone has mk82 unguided bombs by default after rearm. you need to manually choose loadout config and switch to gbu to have gbu's
>also when planes are rearmed the laser designator dissapears
>i have to turn on the laser on laser designator before plane rearm before rearm, otherwise there's no way to turn it on after rearm. there is also no way to turn it off after rearm, so it stays always on

**Comment by Yoshi-E** [comment]
confirmed.
Even if you can rearm UAV you can only do it, if you are physical near it.

**Comment by HTomJMW** [comment]
Service menu list empty if your vehicle not manned… tested with cars. i think UAV not "manned" so you can't see in list.

**Comment by zerty** [comment]
You need to have either a live unit in or be connected to the UAV, working as intended, closing
