### ISSUE TITLE
Rearm for statics broken

### ISSUE THREAD

**Issue by Yoshi-E** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#156]
Automated rearm for statics like the Long range AA does not work most of the time

**Comment by HTomJMW** [comment]
Porblem same as UAV rearm problem. Works better is you connect AAA with terminal.
Hard rearm and repair non Local things...

**Comment by zerty** [comment]
i think its just that those are not taken into account into the rearm and man stuff, the whole defense AI needs to be reworked

**Comment by zerty** [comment]
still a problem with player nits squating automanned statics
