### ISSUE TITLE
new Upgrade: Data Link for players

### ISSUE THREAD

**Issue by Yoshi-E** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#166]
Enabling Data Link allows the player to share his data (e.g Postion and laser designators)

**Comment by zerty** [comment]
can you be more precise?

**Comment by Yoshi-E** [comment]
https://community.bistudio.com/wiki/vehicleReportOwnPosition
https://community.bistudio.com/wiki/setVehicleReportOwnPosition
https://community.bistudio.com/wiki/vehicleReportRemoteTargets
https://community.bistudio.com/wiki/setVehicleReportRemoteTargets
https://community.bistudio.com/wiki/vehicleReceiveRemoteTargets
https://community.bistudio.com/wiki/setVehicleReceiveRemoteTargets


For players, so they can correctly use laser targeting, be visible via sensors, or for other vehicles e.g radar vehicles / aircraft to report their position to the team.

This makes targeting and radar sharing alot easier

**Comment by Yoshi-E** [comment]
36560608d9878a5d5e75395936bcaadb5af36250

**Comment by johnsmm** [comment]
you guys seen this causing any slow downs ? esp when some one gets in air like in a jet ?
