### ISSUE TITLE
Purchase Order Failed - "STR_OnPurchase_NotFunds"

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#174]
When you buy Unit/Vehicle and you DIE before it is arriving, you get "not enough founds" message and order skipping.
Something wrong with Client\Functions\Clien_OnPurchaseOrderReceived.sqf line 124, 125.
It's worked once when you start buy: line 91, 94 with alive _req_buyer, but line 124, 125 not working with dead _req_buyer.

**Comment by HTomJMW** [comment]
Perfect... All working good!

**Comment by HTomJMW** [comment]
Maybe its make new bug?
Factorys lost build queue… and you can buy several units in same time.
if you buy JET and medpod you will get the medpod first

**Comment by zerty** [comment]
works correctly on my side
