### ISSUE TITLE
Ai commander gets relieved in SP

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#179]
from discord:

```Billa - Today at 7:28 AM
Hey all, trying to play this with an AI commander. However I constantly get spammed "AI has taken command" followed by "AI has been relieved of command".
An idea what my cause this? I'm playing the latest version "01/05/2018 :: Release of 1.3.2.8 HTom"
Playing local MP (starting a LAN game through the server browser) ```

**Comment by AshEdwardsDesign** [comment]
Hey Zerty, Billa here (guy who reported this).

The AI does evantually take over the commander position, it simply takes a few failed attempts for some reason (please see screenshot).

So this isn't really an issue. I'm not sure if you want to look into what causes this though just out of curiosity? When I first encountered this I thought that the AI couldn't take command and I almost didn't continue playing :P

![arma3-zerty-ai-comm](https://user-images.githubusercontent.com/8330786/41016083-42aa85de-6988-11e8-95fd-41b02b86994d.png)
