### ISSUE TITLE
Script error when On ruin cleanup.

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#186]
Sometimes i see script error when HQ or maybe factorys down.

22:30:35 Error in expression <x}} forEach (nearestObjects [_position, _classnames, 25])};>
22:30:35   Error position: <_classnames, 25])};>
22:30:35   Error Undefined variable in expression: _classnames
22:30:35 Error in expression <ce getVariable _variable;
_classnames = _var select 1;
_classnames = if (count _>
22:30:35   Error position: <_var select 1;
_classnames = if (count _>
22:30:35   Error Undefined variable in expression: _var

**Comment by zerty** [comment]
Related to the ruin cleanup process
