### ISSUE TITLE
Unit order lines on Map Commanding screen are too thin

### ISSUE THREAD

**Issue by AshEdwardsDesign** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#205]
Hi Zerty,

Just providing a screenshot relating to the issue I mentioned on discord about the order lines on the "Map Commanding" screen being too thin.

Please see the attached screenshot. You'll see the very thin lines I'm talking about (sometimes they are very hard to see). A slight increase in thickness would be helpful :)

![map-commanding-order-lines](https://user-images.githubusercontent.com/8330786/41022510-c793f7a0-69a4-11e8-8be5-db70da9b6203.png)

**Comment by zerty** [comment]
Connot be modified, its inherent to https://community.bistudio.com/wiki/drawLine
