### ISSUE TITLE
Noob protection repair the HQ

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#208]
Wheel protection try repair MHQ wreck when you shoot tires.
Every hit send HQ down message and make blows. If server lagging you can get reward too.

**Comment by zerty** [comment]
Its not the weal protection but the noob protection. Realted to the grenade repairing lost weels on the HQ

**Comment by zerty** [comment]
Lets call it a feature. Closing
