### ISSUE TITLE
Our Units killing by friendly mines.

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#209]
Friendly Units don't knows friendly mines.
We can't use mines in towns because Towns Occ killing by friendly fire. -> JAIL....

**Comment by HTomJMW** [comment]
Only miners keep distance from mines. (detector)

**Comment by HTomJMW** [comment]
working with Eventhandler "fired"... so if mine dispernser shoot ammo out, we can't get info from the little mines....
also not working if AI put mine... only for players

**Comment by zerty** [comment]
gj
