### ISSUE TITLE
AI skill for players is to low

### ISSUE THREAD

**Issue by Yoshi-E** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#218]
need to check ai skill

**Comment by Yoshi-E** [comment]
https://github.com/zerty/Benny-Edition-CTI-0.97-Zerty-Modification/blob/7c65ad90169247f86df6850e956e795d5355fde4/Addons/AiRandomSkill/RandomSkill.sqf#L57-L67

Return 0.4 for all values

**Comment by HTomJMW** [comment]
its ok... 
skill ai; give 0.41 but dosent matter

ai skill "spottime" give 0.7-1

**Comment by HTomJMW** [comment]
all spawned ais uses random skill script

TO equal to player's ais
