### ISSUE TITLE
Spawn distance Naval

### ISSUE THREAD

**Issue by Yoshi-E** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#220]
[8:40 PM] pace:  Naval Yard spawns boats far away. Noticed today on Altis: 
approx 1 km south of it, the boats are spawning on land
https://cdn.discordapp.com/attachments/315423338837180429/466675284767146000/naval_bug.jpg

**Comment by HTomJMW** [comment]
https://github.com/zerty/Benny-Edition-CTI-0.97-Zerty-Modification/blob/bug-fixing/Common/Functions/Common_CreateVehicle.sqf#L107

**Comment by Yoshi-E** [comment]
didn't happen again, does not seem to occur very often, closed for now

**Comment by HTomJMW** [comment]
if no good water position ships spawn near AAC S1000
