### ISSUE TITLE
Town occupation FSM

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#224]
Enemy units remove only after 240s (cti_towns_inactive_max)
Timeout box -> &&
fast deactivation not possible

**Comment by HTomJMW** [comment]
maybe same as #116

**Comment by Yoshi-E** [comment]
If you active an enemy (not Independent) town, their forces will remain for at least 240s even if you force deactivate the town. Though I would say this is working as Intended.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zerty** [comment]
it is working as intented then, closing
