### ISSUE TITLE
Enable Mine markers on map

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#226]

**Comment by HTomJMW** [comment]
![known_mines](https://user-images.githubusercontent.com/31548102/43686910-776758a0-98cd-11e8-95c3-45216269aeeb.jpg)

known mines with TADST settings

**Comment by Yoshi-E** [comment]
Has to be enable in the difficulty setting.
detectedMines = show

**Comment by Yoshi-E** [comment]
I assume the current situation is as desired
