### ISSUE TITLE
Interaction menu when you remote AI

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#232]
Your AI can't attach pod, take ammo box or use other interaction menu things when you remote the AI.
Menu always showing the player interaction possibilities and not the AI's.

**Comment by zerty** [comment]
accessing the menu through remote AI is not planned, the gug is that the menu shows up when remote ai is taken, i am not sure i want to extend this bug as a feature ...

**Comment by HTomJMW** [comment]
then just need enable only "tablet" on interaction menu until u controlling the AI
