### ISSUE TITLE
Datalink markers

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#234]
![dead](https://user-images.githubusercontent.com/31548102/44298596-2911a480-a2e6-11e8-9379-04cd6a4d0114.jpg) - Tank wreck on central of picture
Dead unit's maker color not changing to black when vehicle down. You don't know vehicle repairable/capturable by enemy or not.
Need wait some mins for wreck clean up...

**Comment by zerty** [comment]
rewriten closing
