### ISSUE TITLE
enemy units sometimes leaked to wrong network

### ISSUE THREAD

**Issue by Yoshi-E** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#235]
Sometimes you can see Independent units from enemy net

**Comment by zerty** [comment]
you need to filter the target before sending to enemy network at line https://github.com/zerty/Benny-Edition-CTI-0.97-Zerty-Modification/blob/77c8766a2501b20410158f84d8d23e0a3187296a/Addons/Strat_mode/HUD/HUD_GetTargets.sqf#L39

**Comment by zerty** [comment]
rewriten, closing
