### ISSUE TITLE
Gear overload

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#24]
1) You have a Titan Launcher with an At middle loaded
2) You purchase Equipment from the Menu with 95-100% load (Titan missile is empty)
3) Parts, magazines, ammo... Is disappearing. 

Reason: The missile inside the Titan Launcher you already have is not being removed when you purchase new gear raising the capacity of the new Equipment over 100% (about 115%). It's not possible to add more than 100% Equipment, so the stuff that gets added last can not be added (usually the GPS, Rangfinder, Weapon, Chestplate)

**Comment by Yoshi-E** [comment]
Bis changed handeling of to heavy gear, loading >100% is now possible
