### ISSUE TITLE
Blurry corner on screen after failed halo jump

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#250]

**Comment by HTomJMW** [comment]
![1111](https://user-images.githubusercontent.com/31548102/44944883-f33ce780-adde-11e8-8c74-714d9477d089.jpg)

maybe need remove this effect manually when player repsawning
fully random not happening always. i think its caused by low fps.
also grenade/blowing sand effect can do this

**Comment by Yoshi-E** [comment]
Looks like the effect is caused whenever you die in free fall.
As i have found no way to get the pp effect handle, the only other solution would be to make sure the player does not die while in free fall.

EventHandle --> dmg --> change animation state before killing the player.

**Comment by Yoshi-E** [comment]
scratch that, found another solution:
`for '_i' from 0 to 499 step 1 do {
	if (ppEffectEnabled _i) then {
		_i ppEffectEnable FALSE;
		_i ppEffectCommit 0;
	};
}`
