### ISSUE TITLE
Stucked TASKS

### ISSUE THREAD

**Issue by HTomJMW** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#261]

**Comment by HTomJMW** [comment]
Checked Malden Town15
Attack TASK marked but town not active by east or west and no patrol there.
town15 not on TASKS_LIST

**Comment by HTomJMW** [comment]
Game restart fixed the problem only tasks_list objects loaded back...
(simpleTasks player;) tasks was not Matched with TASKS_LIST, maybe need do cleanup in simpleTasks too

**Comment by zerty** [comment]
c83df4ca327ab212dc5bef18a717f784d3576061
25dcb5e661728edc6f074abfd09c7f4462b61ed3

**Comment by zerty** [comment]
85dbe265dfd2c44ceb3cfe7770d0709748957176 should fix
