### ISSUE TITLE
Remote control release getting players stuck

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#276]
Using  remote then switching back to 1st person player sometimes seems bugged, getting trapped in vehicle unable to return to player view despite releasing UAV controls.

**Comment by HTomJMW** [comment]
rare bug. ingame fix -> u need remote again and get out with ai from vehicle

**Comment by HTomJMW** [comment]
update:
You need take UAV control and release for fix ingame.
problem is Remote control action in common_createunit.sqf
the rev script can't release because it not uavconnection...

**Comment by HTomJMW** [comment]
zeus cam can do same bug when u remote ai

**Comment by HTomJMW** [comment]
uav cam ok
i hope not need reopen this issue later
