### ISSUE TITLE
Bad performance with Pre-Release 1/2 version

### ISSUE THREAD

**Issue by DartNecrON** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#28]
CPS drop every 10 mins after caching scripts change, im rolling back to 1.3.0.6

**Comment by zerty** [comment]
yeah i know I have disabled the script in the latest commits 2fa70156b48e76eaa984c072c9cf90231daef95f  still one bug : caching system is still getting activated for no apparent reason.
