### ISSUE TITLE
No Entry

### ISSUE THREAD

**Issue by DoctorDizzee** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#296]
While loading in I got a continuous error of "No entry 'bin/CfgWorlds.97-Zerty-Modification-master'."

![image](https://user-images.githubusercontent.com/53086865/79083094-7fb8c700-7cf1-11ea-91ec-cfd33a8b4c1c.png)

**Comment by zerty** [comment]
strange can tou send us the RPT for that error?

**Comment by DoctorDizzee** [comment]
Not exactly sure where I could generate a error report, but this is what it looks like from the server side.
P.S. This is my most favorite game mode in Arma 3. Love your work!
![image](https://user-images.githubusercontent.com/53086865/79161207-b13c9b80-7da0-11ea-8844-9ff9785d3955.png)

**Comment by DoctorDizzee** [comment]
I think I found it. If thats not it please let me know. Also idk if this is important but I am using TADST.
[netlog-31568-2020-04-13_17-27-03.log](https://github.com/zerty/Benny-Edition-CTI-0.97-Zerty-Modification/files/4471966/netlog-31568-2020-04-13_17-27-03.log)

**Comment by HTomJMW** [comment]
is it a .PBO file in ....\Steam\steamapps\common\Arma 3\MPMissions folder?

**Comment by HTomJMW** [comment]
https://github.com/HTomJMW/up/raw/master/becti_current.Altis.pbo
try it with this version of pbo

**Comment by DoctorDizzee** [comment]
That one works fine thank you :)
