### ISSUE TITLE
Units on Debug Island

### ISSUE THREAD

**Issue by Yoshi-EE** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#35]
1.3.1.0 pre4

As seen on the screenshot: Opfor debug Island is empty, no units there, Bluefore Island seems fine. Dead soldiers stacked up on the corner of the map, probably opfor bodies.

![2015-04-19_00006](https://cloud.githubusercontent.com/assets/11833269/7221330/f6255436-e6e6-11e4-9f5e-97b15b459ebf.jpg)

**Comment by zerty** [comment]
No those are the bodies and objects that are to be removed by the garbage collector and empty vehice tracker
