### ISSUE TITLE
Find a way to change vehicle com on mixed AI - player group

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#4]
Currently, a non leader player will have some issues with vehicle with AI of its own group

**Comment by zerty** [comment]
No solutions available, Ill see later for that one

**Comment by MKalat** [comment]
Maybe Arma 3 bug ? Not everything is possible to fix, somehow and someties still broken a bit pathfindig in example.

**Comment by zerty** [comment]
Found a solution by changing the rank of player units. But a bohemia command like a seteffectivecommander would be better.
