### ISSUE TITLE
Rework the vehicle lock 

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#5]
ATM: Only the buyer keep the hand on the vehicle lock whatever his group his, migth need to rethink that.

**Comment by MKalat** [comment]
In one of new versions of mission I had situation, that friendly team bought vehicles, but its soliders were to far away to use that vehicles, so these vehicles were stacking one by one near factory until space for spawned vehicles finished and the factory got destroyed by one on spawning vehicles. If I could take this vehicels out of spawn zone, I could save factories, but vehicle lock prevented this. I guess commander should have keys for all assets of the side. He's commander, isn't he ? ;)

**Comment by zerty** [comment]
Yeah, I think I'll add some olock overide for the commander
