### ISSUE TITLE
Handle AI Purchases

### ISSUE THREAD

**Issue by baluballa** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#51]
If buing a heli to an AI group. It seems to be filled with Pilots in all places. Think it can be becuase of Server_HandleAIPurchase.sqf line 119.

**Comment by zerty** [comment]
Yeah all that is related to the AI groups not being handled in this version.
1310 is not suitable to play with AI group yet 1.3.0.6 was the las one working with those

**Comment by baluballa** [comment]
Ok, I can't find any download locations for that version. Do you know where I can get it?

**Comment by zerty** [comment]
http://www.jammywarfare.eu/mpmissions/

**Comment by baluballa** [comment]
Thanks, let me know if I can contribute in anyway.
