### ISSUE TITLE
Loading into the mission

### ISSUE THREAD

**Issue by Yoshi-EE** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#69]
When the server run for some time in the same mission, and you join, you start with 0$ until the money you had previously loaded in. But that can sometime take up to 10min... and all the money thats being send to you during that time gets removed after loading your previous cash/start cash.

**Comment by Yoshi-EE** [comment]
Waiting for Server to approve connection also take some times over 5min... 
Some loops in the script maybe?

**Comment by Yoshi-EE** [comment]
loops confrimed 600.000 lines, before the script quit: 
Wrong Player Index Passed to GetPlayerObjectinfo - max=1, received=6;
Wrong Player Index Passed to GetPlayerObjectinfo - max=1, received=4;
Wrong Player Index Passed to GetPlayerObjectinfo - max=1, received=2;
Wrong Player Index Passed to GetPlayerObjectinfo - max=1, received=5;
Wrong Player Index Passed to GetPlayerObjectinfo - max=2, received=6;
Wrong Player Index Passed to GetPlayerObjectinfo - max=2, received=4;
Wrong Player Index Passed to GetPlayerObjectinfo - max=2, received=3;
Wrong Player Index Passed to GetPlayerObjectinfo - max=3, received=5;

**Comment by zerty** [comment]
ill check it when I RTB, bout a week or so from now

**Comment by zerty** [comment]
seems that bohemia fucked something in the player stack when the connection is started, other server admins seems to report the same rpt spam

**Comment by zerty** [comment]
Partially solved, still lag sensitive
