### ISSUE TITLE
Integrate RHS units + parameter

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#8]
Also needs a parammeter to completelly swithch from vannila to RHS

**Comment by DartNecrON** [comment]
I can upload my RHS version i'm running but some functions have to be added

**Comment by zerty** [comment]
more up 2 date @ https://github.com/luggage66/BECTI-ZERTY-RHS.Altis

**Comment by luggage66** [comment]
Ours was based on DartNecrON's work.

**Comment by zerty** [comment]
yeah i saw that, And you keep good credits on the mission so no need for me to do it on main branch.

Keep up the good work

**Comment by LeerianDark** [comment]
Is there any possibility to play this with RHS? i tried the Link but it isnt up 2 date anymore....
