### ISSUE TITLE
Integrate TFR 

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#9]

**Comment by DartNecrON** [comment]
Gear_East.sqf

_i = _i		+ ["tf_mr3000_rhs"];
_u = _u		+ [0];
_p = _p		+ [55];

_i = _i		+ ["tf_fadak"];
_u = _u		+ [0];
_p = _p		+ [500];

_i = _i		+ ["tf_pnr1000a"];
_u = _u		+ [0];
_p = _p		+ [100];

_i = _i		+ ["tf_mr3000"];
_u = _u		+ [0];
_p = _p		+ [200];

_i = _i		+ ["tf_mr3000_multicam"];
_u = _u		+ [0];
_p = _p		+ [200];

_i = _i		+ ["tf_mr6000l"];
_u = _u		+ [0];
_p = _p		+ [1000];
//
Gear_West.sqf
_i = _i		+ ["tf_rt1523g_rhs"];
_u = _u		+ [0];
_p = _p		+ [55];

_i = _i		+ ["tf_anprc152"];
_u = _u		+ [0];
_p = _p		+ [500];

_i = _i		+ ["tf_rf7800str"];
_u = _u		+ [0];
_p = _p		+ [100];

_i = _i		+ ["tf_rt1523g"];
_u = _u		+ [0];
_p = _p		+ [200];

_i = _i		+ ["tf_rt1523g_big"];
_u = _u		+ [0];
_p = _p		+ [250];

_i = _i		+ ["tf_rt1523g_black"];
_u = _u		+ [0];
_p = _p		+ [250];

_i = _i		+ ["tf_rt1523g_fabric"];
_u = _u		+ [0];
_p = _p		+ [250];

_i = _i		+ ["tf_rt1523g_green"];
_u = _u		+ [0];
_p = _p		+ [250];

_i = _i		+ ["tf_rt1523g_sage"];
_u = _u		+ [0];
_p = _p		+ [250];

_i = _i		+ ["tf_anarc210"];
_u = _u		+ [0];
_p = _p		+ [1000];

//prices to be edited

**Comment by zerty** [comment]
thanks, i ll add it
