### ISSUE TITLE
Add option to sell/remove base area

### ISSUE THREAD

**Issue by Liveandletdie** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#93]
Allow commanders to sell/remove base areas, so that they can move a base to new location once a base has been destroyed or becomes otherwise necessary to move.

**Comment by zerty** [comment]
Actually its not really a bug but more a feature that prevent games to run forever ( by preventing sneaky coms to rebuild a base as soon as the previous one is compromised). So i wont fix that for the moment but ill do something in te near future for base area to be recycled, linked to the value of a parametter.

**Comment by Liveandletdie** [comment]
One of the main reasons i posted this issue is because I have been in several games when commanders build in one location and accidentally place a building just outside the circle another base area gets placed in the same area. When is occurs it really limits a team as 2 base areas gets wasted on one location with no way to fix it. If we had an option to sell base areas this would be fixed, or if you can come up with another way to prevent this from happening....plus it is always useful as a commander to be able to move a base if both base areas have been under heavy attack/leveled.

On an older OFPS version they had a military tower which would act as the base area, you would need to place this structure first which would set the area, then if you tried to build outside the area it would not allow you to build.

**Comment by Liveandletdie** [comment]
Hey i was working on some updates regarding selling bases and i have selling of bases nailed down but i cant seem to remove the area markers (diaggrid) and associated town links, what part of the code controls this? cti_structures_areas? how would i go about adding in a function to delete it when selling a base?

PS: is there any other way to contact you regarding coding questions?
