### ISSUE TITLE
MHQ repair issues

### ISSUE THREAD

**Issue by Liveandletdie** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#95]
So this issue doesn't come up a ton but i have been in several games in which if the mhq gets blown up inside or around certain structures (sheds, dome, buildings) it becomes a serious pain or almost impossible to repair, ie when you repair the mhq it just blows up immediately on spawn because of the location or its glitched into a structure. It can also happen if lets say a mhq gets blown up underwater, there is no way to repair/recover. We need an option to either have a timer refund your repair cash if the mhq immediately blows on respawn (like 5sec) and/or have an option to rebuild the MHQ from the cc.

**Comment by zerty** [comment]
Problem still present

**Comment by zerty** [comment]
Closing for now
