### ISSUE TITLE
Resistance Units under player control

### ISSUE THREAD

**Issue by G-Sgt-Hartman** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#96]
I've read posts from other players on using Zeus to control resistance units.  Would be a great challenge to fight against resistance controlled by players rather then the same dumb ai all the time.  Seeing as you have great ideas Zerty, I'm sure you could implement this into BECTI.

**Comment by zerty** [comment]
In fact, more that a year ago we did some test with controlled player resistance combined with zeus. Sadly we never succeeded to create a balanced gameplay that way.

**Comment by G-Sgt-Hartman** [comment]
That's too bad. So you don't think there's a way to get back into it?

**Comment by zerty** [comment]
Not really for now, since we have not come up with a coherent gameplay that will provide entertaiment while keeping the game balanced for every team. Postponed

**Comment by zerty** [comment]
Non viable option
