### ISSUE TITLE
Preventing SkillStack

### ISSUE THREAD

**Issue by zerty** [zerty/Benny-Edition-CTI-0.97-Zerty-Modification#99]

**Comment by G-Sgt-Hartman** [comment]
This is an interesting one, how in the world are you going to do it?

**Comment by MagnetAss** [comment]
I've been scratching my head on this one for almost a year...

**Comment by zerty** [comment]
Not exactly sure yet, but the basic idea is 
-The client store its own (Total Score / Total Time on the mission) value
-The server store & update the median value + deviation 
-On join the client send its value
-If time is too low no effect
-if the Client value is > to the median + (1 to 3)*Deviation^2 then the player is considered  a proplayer
-Check the numbers of proplayers per team
-Then anti-skillstack of proplayer
-This process has priority over teamstack and teamswap protection

The main problem is now how to allow 2 proplayers from the same unit to play together
